### ISSUE TITLE
Get Topiary working with mice

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/topiary#13]
- [x] Get `pyensembl` working with arbitary GTFs (including updating `release_info.py`, `common.py`, `url_templates.py`, etc. to not be human specific); see https://github.com/hammerlab/pyensembl/pull/99
- [x] Change `varcode`'s `reference_name.py` (which is currently human specific); see https://github.com/hammerlab/varcode/pull/106
- [x] Already done? Mice in `mhctools`'s `alleles.py`

**Comment by iskandr** [comment]
Fixed by https://github.com/hammerlab/pyensembl/pull/114 and https://github.com/hammerlab/varcode/pull/118
