### ISSUE TITLE
Add NetMHCIIpan as a predictor

### ISSUE THREAD

**Issue by iskandr** [hammerlab/topiary#14]
From Kipp Akers:

>So I tried in vain to add a bit of code to topiary so that it would take NetMHCIIpan as an input/prediction method, but it keeps dying with the message that one of the arguments  mhc-cons, mhc-smm-iedb etc etc is required.

**Comment by timodonnell** [comment]
+1 We have another group interested in topiary for class II

**Comment by iskandr** [comment]
We have basic support, though we currently ignore the binding core: https://github.com/hammerlab/topiary/issues/36
