### ISSUE TITLE
Question: How are frameshifts handled?

### ISSUE THREAD

**Issue by kippakers** [hammerlab/topiary#55]
I'm getting interesting results w/r/t frameshifts in my data.  A large percentage of my self-ligandome identical epitopes are from frameshifts (3511/3648), which was surprising.

My guess from a bit of reverse engineering is that you take the cDNA sequence, add the in/del, then run it through translation software, looking for the largest ORF.  Is that right?  I think that makes good sense too, I just want to understand. 

Thanks,
Kipp

**Comment by iskandr** [comment]
Hey Kipp, 

There was a pretty tragic bug in Varcode which mis-translated some frameshifts: https://github.com/hammerlab/varcode/issues/151

I would upgrade Varcode before trusting any translated frameshifts. I'm sorry for the hassle!

As for how the translation happens: you have it pretty much right except that there's no need to select the longest ORF, a unique ORF should still be discernable after applying an indel to the reference sequence.

**Comment by kippakers** [comment]
Ha! I missed that update by ~ 2 hours.  I'll give it a rerun and see how the frameshifts look.  Thanks!
