### ISSUE TITLE
'Namespace' object has no attribute 'rna_gene_fpkm_file'

### ISSUE THREAD

**Issue by cedarice** [hammerlab/topiary#59]
Hey guys,
My command line input:

topiary --vcf Hep-3B2.FilterOut1000G.vcf --mhc-predictor netmhcpan --mhc-alleles HLA-A*74:01,HLA-A*68:02 --ic50-cutoff 500 --percentile-cutoff 2.0 --mhc-epitope-length 8-11 --rna-gene-fpkm-tracking-file genes.fpkm_tracking --rna-min-gene-expression 4.0 --rna-transcript-fpkm-tracking-file isoforms.fpkm_tracking --rna-min-transcript-expression 1.5 --output-csv Hep-3B2.epitopes.csv --output-html Hep-3B2.epitope.html --rna-transcript-fpkm-gtf-file transcripts.gtf

But get the following errors:
Topiary commandline arguments:
Namespace(ic50_cutoff=500.0, json_variant_files=[], maf=[], mhc_alleles='HLA-A*74:01,HLA-A*68:02', mhc_alleles_file=None, mhc_epitope_lengths=[8, 9, 10, 11], mhc_predictor='netmhcpan', only_novel_epitopes=False, output_csv='Hep-3B2.epitopes.csv', output_csv_sep=',', output_html='Hep-3B2.epitope.html', padding_around_mutation=None, percentile_cutoff=2.0, print_columns=False, reference_name=None, rename_output_column=None, rna_gene_fpkm_tracking_file='genes.fpkm_tracking', rna_min_gene_expression=4.0, rna_min_transcript_expression=1.5, rna_transcript_fpkm_gtf_file='transcripts.gtf', rna_transcript_fpkm_tracking_file='isoforms.fpkm_tracking', skip_variant_errors=False, subset_output_columns=None, variant=[], vcf=['Hep-3B2.FilterOut1000G.vcf'], wildtype_ligandome_directory=None)
INFO:root:Building MHC binding prediction type for alleles ['HLA-A*74:01', 'HLA-A*68:02'] and epitope lengths [8, 9, 10, 11]
INFO:root:Skipping allele SLA-1-CHANGDA: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB01: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB02: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB03: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-HB04: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-LWH: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-TPK: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-YC: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-YDL01: Malformed MHC type 1
INFO:root:Skipping allele SLA-1-YTH: Malformed MHC type 1
INFO:root:Skipping allele SLA-2-YDL02: Malformed MHC type 2
INFO:root:Skipping allele SLA-3-CDY: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-HB01: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-LWH: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-TPK: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YC: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YDL: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YDY01: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YDY02: Malformed MHC type 3
INFO:root:Skipping allele SLA-3-YTH: Malformed MHC type 3
INFO:root:Skipping allele H-2-Qa2: Malformed mouse MHC allele: H-2-Qa2, parse error at a2
INFO:root:Skipping allele H-2-Qa1: Malformed mouse MHC allele: H-2-Qa1, parse error at a1
Traceback (most recent call last):
  File "/home/qianlab/soft/topiary/ENV/bin/topiary", line 4, in <module>
    __import__('pkg_resources').run_script('topiary==0.0.20', 'topiary')
  File "/home/qianlab/soft/topiary/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/qianlab/soft/topiary/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/qianlab/soft/topiary/ENV/lib/python2.7/site-packages/topiary-0.0.20-py2.7.egg/EGG-INFO/scripts/topiary", line 58, in <module>
    main(args)
  File "/home/qianlab/soft/topiary/ENV/lib/python2.7/site-packages/topiary-0.0.20-py2.7.egg/EGG-INFO/scripts/topiary", line 43, in main
    epitopes = predict_epitopes_from_args(args)
  File "/home/qianlab/soft/topiary/ENV/local/lib/python2.7/site-packages/topiary-0.0.20-py2.7.egg/topiary/predict_epitopes.py", line 277, in predict_epitopes_from_args
    gene_expression_dict = rna_gene_expression_dict_from_args(args)
  File "/home/qianlab/soft/topiary/ENV/local/lib/python2.7/site-packages/topiary-0.0.20-py2.7.egg/topiary/commandline_args/rna.py", line 72, in rna_gene_expression_dict_from_args
    return load_cufflinks_fpkm_dict(args.rna_gene_fpkm_file)
AttributeError: 'Namespace' object has no attribute 'rna_gene_fpkm_file'

Any ideas?

**Comment by iskandr** [comment]
Looks like there was a small typo in parsing of RNA args, should be fixed by: https://github.com/hammerlab/topiary/commit/8a63a0fafe54d1561c1af52468db57ac7f5b440b

**Comment by cedarice** [comment]
It works, thank you!
